### Find All Count
GET http://localhost:8080/api/content

### Get content by id
GET http://localhost:8080/api/content

### new content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "second spring",
  "desc": "2 spring to go",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-06-05T15:05:48.8806924",
  "dateUpdate": null,
  "url": ""
}
### Update
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
"id": 1,
"title": "Update!!!! spring",
"desc": "Update!!!! spring to go",
"status": "IDEA",
"contentType": "ARTICLE",
"dateCreated": "2023-06-05T15:05:48.8806924",
"dateUpdate":  "2023-06-05T15:05:48.8806924",
"url": "http://localhost:8080/firstupdate"
}

### Delete by id
DELETE http://localhost:8080/api/content/2
